name: waterflow
description: "WaterFlow: трекер воды на Flutter с локальным хранением и Riverpod."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.1.0
  home_widget: ^0.8.1
  fl_chart: ^0.66.2
  timezone: ^0.9.2
  uuid: ^4.3.3
  cupertino_icons: ^1.0.6
  yandex_mobileads: ^7.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon_foreground.png
    - assets/icon_background.png
